{"name": "密码缺失", "status": "failed", "statusDetails": {"message": "AssertionError: assert '1' == 1", "trace": "self = <test_allure.TestLogin object at 0x000001F79CFD6C10>\n\n    @allure.story(\"密码缺失\")\n    @allure.title(\"密码缺失\")\n    def test_login_key_miss(self):\n        with allure.step(\"点击用户名\"):\n            print(\"输入用户名\")\n        with allure.step(\"点击密码\"):\n            print(\"输入密码\")\n        print(\"点击登录\")\n        with allure.step(\"点击登录之后登录失败\"):\n>           assert '1' == 1\nE           AssertionError: assert '1' == 1\n\ntest_allure.py:137: AssertionError"}, "steps": [{"name": "点击用户名", "status": "passed", "start": 1622135668292, "stop": 1622135668292}, {"name": "点击密码", "status": "passed", "start": 1622135668292, "stop": 1622135668292}, {"name": "点击登录之后登录失败", "status": "failed", "statusDetails": {"message": "AssertionError: assert '1' == 1\n", "trace": "  File \"C:\\Users\\samuelPC\\PycharmProjects\\unittest_example\\pytest_dir\\test_allure.py\", line 137, in test_login_key_miss\n    assert '1' == 1\n"}, "start": 1622135668292, "stop": 1622135668292}], "attachments": [{"name": "stdout", "source": "356b7e37-cd75-4726-b832-df73018e7d82-attachment.txt", "type": "text/plain"}], "start": 1622135668291, "stop": 1622135668292, "uuid": "a5e7e963-2ca1-4cc8-ab61-cb16fdfbed11", "historyId": "874a0fee9f808accb467f7ea177ecc63", "testCaseId": "1214d735beea91adef8899cf05eff310", "fullName": "test_allure.TestLogin#test_login_key_miss", "labels": [{"name": "story", "value": "密码缺失"}, {"name": "feature", "value": "登录模块"}, {"name": "severity", "value": "normal"}, {"name": "suite", "value": "test_allure"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "LAPTOP-8M09KOLJ"}, {"name": "thread", "value": "4920-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_allure"}]}